// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt2ISOV3rJbhLGQR1MKkEXTb__vSXH-Gc',
    appId: '1:539488694526:web:95f95db78c695719be35af',
    messagingSenderId: '539488694526',
    projectId: 'mu-cs-2dd97',
    authDomain: 'mu-cs-2dd97.firebaseapp.com',
    storageBucket: 'mu-cs-2dd97.firebasestorage.app',
    measurementId: 'G-NBXDSK00J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI5SmfJRDT_Ftwyokid5fyDetUzuLK4f0',
    appId: '1:539488694526:android:0a0ea8f5773647a4be35af',
    messagingSenderId: '539488694526',
    projectId: 'mu-cs-2dd97',
    storageBucket: 'mu-cs-2dd97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfs0RPLRBhzQN2XM9KMmq8YP8EcSAhifc',
    appId: '1:539488694526:ios:5f6691a409fd6cdebe35af',
    messagingSenderId: '539488694526',
    projectId: 'mu-cs-2dd97',
    storageBucket: 'mu-cs-2dd97.firebasestorage.app',
    iosBundleId: 'com.example.mucs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfs0RPLRBhzQN2XM9KMmq8YP8EcSAhifc',
    appId: '1:539488694526:ios:5f6691a409fd6cdebe35af',
    messagingSenderId: '539488694526',
    projectId: 'mu-cs-2dd97',
    storageBucket: 'mu-cs-2dd97.firebasestorage.app',
    iosBundleId: 'com.example.mucs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt2ISOV3rJbhLGQR1MKkEXTb__vSXH-Gc',
    appId: '1:539488694526:web:dae439eea784fa03be35af',
    messagingSenderId: '539488694526',
    projectId: 'mu-cs-2dd97',
    authDomain: 'mu-cs-2dd97.firebaseapp.com',
    storageBucket: 'mu-cs-2dd97.firebasestorage.app',
    measurementId: 'G-C98GGBSR1T',
  );
}
